export const properties = {
  userId: "userId",
  userName: "userName",
  shift:"shift",
  section:"section",
date: "date",
field_1: "field_1",
field_2: "field_2",
field_3: "field_3",
field_4: "field_4",
field_5: "field_5",
line: "line" ,
lineA: "1",
lineB: "2", 
shift1:"A",
shift2:"B",
shift3:"C",
approve:"Approved",
reject:"Rejected",
waiting:"Waiting",
general:"General",
group1:"Group 1",
group2:"Group 2",
group3:"Group 3",
group4:"Group 4",
group5:"Group 5",
group6:"Group 6",
group7:"Group 7",
group8:"Group 8"


};